[package]
name = "aliases"
version = "0.1.2"
edition = "2021"
description = "utilities for adding aliases from CLI programs"
authors = ["Ben Schofield <me@benjscho.dev>"]
license = "MIT"
repository = "https://github.com/Benjscho/aliases"

[dependencies]
anyhow = "1.0.89"
dirs = "5.0.1"
